### PR TITLE
#[UIC-1509] Multiple row selection support in Table viz

### PR DESCRIPTION
**Pull request by ankursinghal2005**
[UIC-1509](https://guavus-jira.atlassian.net/browse/UIC-1509)

### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by bipinsoniguavus** [comment]
@ankursinghal2005  As discussed, we should keep the original table row selection behavior intact where user would keep clicking the rows without the need of toggling the previous the selected row in case of single selection.

**Comment by ankursinghal2005** [comment]
> @ankursinghal2005 As discussed, we should keep the original table row selection behavior intact where user would keep clicking the rows without the need of toggling the previous selected row in case of single selection.

We will provide selection capabilities for table as below-:

click: select element/ de-select element
shift + click: add/remove element to current selection

**Comment by bipinsoniguavus** [comment]
I believe that we should give an option to choose single selection or multi selection of rows in table viz.
@ankursinghal2005 @jitendra-kumawat @rasmi-ranjan-guavus @arpit-agarwal Opinions?

**Comment by ankursinghal2005** [comment]
@bipinsoniguavus I think, this is not useful option to provide in table to enable single and multiple selections. By default it should be enable both. Multiple selections by default is single selection.

**Comment by bipinsoniguavus** [comment]
> @bipinsoniguavus I think, this is not useful option to provide in table to enable single and multiple selections. By default it should be enable both. Multiple selections by default is single selection.

IMO, there should be an option to select single or multi selection, as to avoid human error by user in case. If we compare the behaviour to multi-dropdown component, we prefer to choose to allow single selection or multi selection as per the need. For more table reference, you can check [here](https://datatables.net/extensions/select/examples/initialisation/multi.html)  

Though we can take up this as a separate task in future sprints if we see the urgent requirement coming next days. And with upgrade we might get better table support with such options. 

Rest LGTM

**Comment by arpit-agarwal** [comment]
> shift + click: add/remove element to current selection

This has to work like Mac Finder or ag-grid.  If not let's add a tech debt story for this

**Comment by ankursinghal2005** [comment]
After internal demo with you, we will create debt story if it is not working as per our requirements.

**Pull request merged**
