### PR TITLE
#[UIC-1183] Metrics key Error resolved by implementing mutate_df_columns

### PR DESCRIPTION
**Pull request by sunilratada**
**Description:**
When user select a aggregation (AVG) in metric for line chart and groupby on bints then line chart shows an error

### CODE REVIEW

**Comment by ankursinghal2005** [comment]
We can also solve this Issue to override **mutate_label** in HiveEngineSpec class. in this case. Internally store mapping from mutated label to original label.

if mutate_label method is override in that case, we are renaming data-frame column name with original label.

 if self.mutated_labels:
               df = df.rename(index=str, columns=self.mutated_labels)

@staticmethod
    def mutate_label(label):
        return label.lower()

**Note-:  In hive database result, we are getting all column name in lowercase.** 

I am just writing this info to provide more details to everyone.

**Comment by arpit-agarwal** [comment]
Can anyone explain me how the proposed changes fix this issue?
When is the newly added function is invoked?
What is invocation call stack?
Who it is different from solutions proposed by @ankursinghal2005
What would be label of column in table after query?

**Comment by ankursinghal2005** [comment]
Both solution is perfect and worked for hive query engine.

**Comment by bipinsoniguavus** [comment]
I was following this [PR](https://github.com/apache/incubator-superset/pull/7048) to fix this issue. 
The ideal way would still be using `normalize_column_name()`. Don't digress from the title of the PR but several other PR's related to it were suggesting the same solution, but eventually I am hoping that we will get the proper fix for all the db engines in upcoming OSS upgrade. 

Follow the conversation I was having [here](https://github.com/apache/incubator-superset/pull/7048#discussion_r275696584)

**Comment by arpit-agarwal** [comment]
I see the PR and see where we are heading.

My question is more about understanding the flow for people like me who had not dig deeper in codebase to understand all this lowercase mess.

I am not questioning the approach. I want a whiteboard diagram explaining why proposed fix will fix underlying issue.

If anyone stumble upon this PR down to road he should be able to understand that why this changes fixes the issue listed in description

**Comment by sunilratada** [comment]
RCA : in hive when we query data with Metrics (for example : AVG(avg_callduration)) then in response from hive we get column name changed to 'avg(avg_callduration)'. So when chart tries to map user provided column to hive column it throws error due to Lower case of hive column name.

Solution : Now in models.py file when response get from hive it checks for expected label and if expected labels are not in match with user provided then it replace it with what user provided from query. In db_engine_specs.py file there is no implelmentaion of 'mutate_df_columns' in HiveEngineSpec and due to that it calls method from base class where there is no implementation of checking expected labels. So, I have added 'mutate_df_columns' with expected labels implementation in HiveEngineSpec and problem is resolved. There is already implementation of 'mutate_df_columns' in PinotEngineSpec of db_engine_specs.py

**Pull request merged**
